// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package featurepkg

import (
	"context"
	"feature/internal/application/action"
	"feature/internal/application/resource"
	"feature/internal/persistence/pgrepo"
	"feature/internal/protocol/fiberhandler"
)

// Injectors from wire.go:

func New(ctx context.Context, cfg Config) (*FeatureName, error) {
	db := cfg.Database
	something := pgrepo.NewSomething(db)
	service := action.NewService(something)
	resourceService := resource.NewService(something)
	handler := fiberhandler.NewHandler(service, resourceService)
	featureName := &FeatureName{
		handler: handler,
	}
	return featureName, nil
}
