// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package featurepkg

import (
	"context"
)

// Injectors from wire.go:

func New(ctx context.Context, cfg Config) (*FeatureName, error) {
	featureName := &FeatureName{}
	return featureName, nil
}
